### ISSUE TITLE
Website does not want to add video MP4

### ISSUE THREAD

**Issue by vistafan12** [pxgamer/vidox#10]
If he wants to add a movie, pops up the error "Sorry, only MP4 and MKV files are allowed.", Although the film is in MP4 format.
What to do?

**Comment by owenvoke** [comment]
Didn't think anyone would actually use this. Anyway, I'll take a look. :smile: Cheers for bringing this issue up.

**Comment by vistafan12** [comment]
ok

**Comment by vistafan12** [comment]
@PXgamer add sql file, that fix the problem

**Comment by owenvoke** [comment]
@vistafan12 I was actually thinking of redoing this project in a better way.

**Comment by vistafan12** [comment]
ohh, ok.
btw. can you help with NeoVid (video sharing website project, created by og VBF creators)?
If so, then I invite you to Discord server: https://discord.gg/Ehb2CsM

**Comment by owenvoke** [comment]
@vistafan12 sure, I've joined the group.
