### ISSUE TITLE
Add logo to the README as a larger file

### ISSUE THREAD

**Issue by owenvoke** [pxgamer/vidox#5]
Preferably with text saying vidox next to it, but fine if it's just the logo.

**Comment by sanchit-bansal** [comment]
I will do it. Please assign it to me 

Thank you

**Comment by owenvoke** [comment]
Go ahead @voidestructor. Weirdly I can't assign anyone. :thinking:

**Comment by sanchit-bansal** [comment]
Okay, I will do it then.

**Comment by sanchit-bansal** [comment]
I have done it , Please check and complete :D
